### ISSUE TITLE
2.6.1 created error "cannot load such file addressable"

### ISSUE THREAD

**Issue by hb9358** [jnicklas/capybara#1644] opened 2016-01-27 21:37 UTC
Yesterday, the tests in my project were passing.  Today, the fail because of 

> ". . . /gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- addressable (LoadError)
> 	from /usr/local/rvm/gems/ruby-2.1.3@ion_documentation_engine/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'"

The only 2 gems that changed in the Gemfile.lock in my project between yesterday and today are
- capybara from 2.6.0 to 2.6.1
- selenium-webdriver from 2.49.0 to 2.50.0

Forcing capybara to 2.6.0 resolves the problem and the tests run again.
In the Gemfile.lock of the version that fails, it has addressable listed, so I don't think the gem is missing entirely.
```
capybara (2.6.1)
      addressable
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
```
Why would changing to capybara 2.6.1 be breaking tests?  
Thank you for the help.

**Comment by twalpole** [comment] 2016-01-27 22:09
Hmmm -- it shouldn't be --- 2.6.1 was released because addressable wasn't being included in the current_path_query file - not sure why it would be failing for you.

**Comment by twalpole** [comment] 2016-01-27 22:12
What version of addressable was being loaded in your gemfile.lock?

**Comment by twalpole** [comment] 2016-01-27 22:22
Ok -- found it -- require 'addressable' would require addressable 2.4.0 ---   I will release Capybara 2.6.2 soon to fix that oversight

**Comment by chrismitchell** [comment] 2016-01-27 22:28
Awesome was just about to respond with a sample Gemfile.lock. :+1: 

Thanks

**Comment by rezadehganpour** [comment] 2016-01-27 23:27
I just had a same issue, I resolve the issue by requiring `addressable/uri` in /lib/capybara/queries/current_path_query.rb:1

**Comment by mjgiarlo** [comment] 2016-01-27 23:32
:speech_balloon: @rezadehganpour 
> I just had a same issue, I resolved it by requiring addressable/uri in /lib/capybara/queries/current_path_query.rb:1
> 
> this is because the addressable is not a file

It is in addressable 2.4.0. The issue is that Capybara 2.6.0 created a dependency on addressable 2.4.0 but its gemspec allows any version of addressable. Changing the `require`  statement in current_path_query.rb, like you did, seems a better solution than constraining the version of addressable in the Capybara gemspec.

Thanks for reporting this @hb9358, and for starting to work on a fix, @jnicklas!

**Comment by twalpole** [comment] 2016-01-27 23:43
2.6.2 released - should be fixed

**Closed by twalpole** 2016-01-27 23:43 UTC

**Comment by mjgiarlo** [comment] 2016-01-27 23:51
:clap: @twalpole

**Comment by chrismitchell** [comment] 2016-01-28 04:39
2.6.2 fixed the issue for me, thanks @twalpole and @hb9358 for reporting.

**Comment by rezadehganpour** [comment] 2016-01-28 04:41
Yea same here. thanks!
