### ISSUE TITLE
Session reset times out if alert already present when trying to close the page

### ISSUE THREAD

**Issue by jnicklas** [jnicklas/capybara#1696] opened 2016-05-09 14:20 UTC
#1672 introduced behaviour which tries to make sure that resetting the session is going to close any alerts from a `beforeunload` handler. Unfortunately, if such an alert is already open, there's a race condition where Capybara never navigates to about:blank and thus gets stuck in a loop trying to check for no content, which never happens. This causes the session reset to time out with an error like:

```
/Users/jonasnicklas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/capybara-2.7.0/lib/capybara/selenium/driver.rb:114:in `reset!': Timed out waiting for Selenium session reset (Capybara::ExpectationNotMet)
	from /Users/jonasnicklas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/capybara-2.7.0/lib/capybara/session.rb:109:in `reset!'
	from test.rb:10:in `<main>'
```

I have a repro [here](https://gist.github.com/jnicklas/a2ada84190f2cc9fdb95acec6a235dde). I'll try to submit a fix.

**Comment by twalpole** [comment] 2016-05-09 22:42
This issue is caused by selenium defaulting to dismissing unexpected alerts, which causes the navigation to about:blank to abort.  We catch this and attempt to accept the alert, but since the alert has already been dismissed seleniums alertTimeout (which I don't see a way to override but might be missing something) takes over and selenium waits for 2 seconds before telling us the modal has already gone away - cycle repeats until we timeout.  I've created PR #1698 which changes the default to ignoring (not dismissing or accepting) unexpected alerts so we can accept it.

**Comment by twalpole** [comment] 2016-05-11 17:53
Fixed via PR #1698

**Closed by twalpole** 2016-05-11 17:53 UTC

**Comment by dunban1** [comment] 2018-05-09 20:52
This error seems to still manifest when using the FF profile setup.

I reproduced it using:
- ruby-2.3.0 

gems:
- capybara (3.0.2) 
- rspec (3.6.0) 
- selenium-webdriver (3.11.0) 

driver:
- geckodriver 0.20.1 


```
Capybara.register_driver :selenium do |app|
    options = Selenium::WebDriver::Firefox::Options.new
    options.profile = 'default'
    desired_caps = Selenium::WebDriver::Remote::Capabilities.firefox(
      {
        marionette: true,
        accept_insecure_certs: true,
      }
    )
    
    Capybara::Selenium::Driver.new(
      app,
      browser: :firefox,
      options: options,
      desired_capabilities: desired_caps
    )
  end
  Capybara.current_driver = :selenium
 Capybara.default_max_wait_time = (20).to_i

describe 'TEST', :js => true, :type => :feature do
  it "test close page" do
    visit 'http://localhost:5050/alert-test.html'
    page.current_window.resize_to 1024, 768
    within("div[name='result']") do
      page.accept_alert do
        click_button "Try it"
      end
    end 
    sleep 5
  end
end

```
I tested it on the following HTML code which is in alert-test.html:

```
<!DOCTYPE html>
<html>
<body>

<h2>JavaScript Alert</h2>
<div name="result">
  <button onclick="myFunction()">Try it</button>  
</div>

<script>
function myFunction() {
    if (confirm("Close Window?")) {
      var placeholder = 0;
    }
}
</script>

</body>
</html>
```

The result is the error message:

`Timed out waiting for Selenium session reset (Capybara::ExpectationNotMet)`

I reproduced it using my setup here if you want to check my Gemfile.lock and ruby version: [https://github.com/nicholasdunbar/cucumber-sandbox](https://github.com/nicholasdunbar/cucumber-sandbox)

**Comment by twalpole** [comment] 2018-05-09 21:08
@dunban1 Do you have that test in a version I can run?  It doesn't actually appear to be in the repo you linked to.  I'm guessing it's a geckodriver/firefox bug though since it's pretty basic behavior

**Comment by dunban1** [comment] 2018-05-09 22:55
@twalpole  I've temporarily added it to the code in the github repo under [https://github.com/nicholasdunbar/cucumber-sandbox/blob/master/spec/example-rspec-capybara.rb](https://github.com/nicholasdunbar/cucumber-sandbox/blob/master/spec/example-rspec-capybara.rb) 

when you clone the repo you can run it from the project base directory by running:

`rspec spec/example-rspec-capybara.rb`

**Comment by dunban1** [comment] 2018-05-10 17:45
@twalpole  Sorry, I forgot about that. All you have to do is set BROWSER=FIREFOX-SAVED-PROFILE in 
https://github.com/nicholasdunbar/cucumber-sandbox/blob/master/spec/.env

**Comment by twalpole** [comment] 2018-05-10 19:48
@dunban1 That passes every time for me.  I am testing with FF 61.0b3 so it's possible it's a bug in a previous version (you don't state what version you're testing with)

**Comment by dunban1** [comment] 2018-05-10 20:05
@twalpole FF 59.0.3 and MacOS HighSierra 10.13.4 
I'll update FF and try again as well.

**Comment by dunban1** [comment] 2018-05-10 20:18
@twalpole I upgraded to FF60 (latest production version) and I still get:

```
1) EXAMPLE TESTS ssl cert
     Failure/Error: raise Capybara::ExpectationNotMet, 'Timed out waiting for Selenium session reset' if (Capybara::Helpers.monotonic_time - start_time) >= 10

     Capybara::ExpectationNotMet:
       Timed out waiting for Selenium session reset
     # /Users/dunban1/.rvm/gems/ruby-2.3.0@rspec/gems/capybara-3.0.2/lib/capybara/selenium/driver.rb:137:in `reset!'
     # /Users/dunban1/.rvm/gems/ruby-2.3.0@rspec/gems/capybara-3.0.2/lib/capybara/session.rb:126:in `reset!'
     # /Users/dunban1/.rvm/gems/ruby-2.3.0@rspec/gems/capybara-3.0.2/lib/capybara.rb:308:in `block in reset_sessions!'
     # /Users/dunban1/.rvm/gems/ruby-2.3.0@rspec/gems/capybara-3.0.2/lib/capybara.rb:308:in `reverse_each'
     # /Users/dunban1/.rvm/gems/ruby-2.3.0@rspec/gems/capybara-3.0.2/lib/capybara.rb:308:in `reset_sessions!'
     # /Users/dunban1/.rvm/gems/ruby-2.3.0@rspec/gems/capybara-3.0.2/lib/capybara/rspec.rb:18:in `block (2 levels) in <top (required)>'

  2) EXAMPLE TESTS close page with alert open
     Failure/Error: raise Capybara::ExpectationNotMet, 'Timed out waiting for Selenium session reset' if (Capybara::Helpers.monotonic_time - start_time) >= 10

     Capybara::ExpectationNotMet:
       Timed out waiting for Selenium session reset
     # /Users/dunban1/.rvm/gems/ruby-2.3.0@rspec/gems/capybara-3.0.2/lib/capybara/selenium/driver.rb:137:in `reset!'
     # /Users/dunban1/.rvm/gems/ruby-2.3.0@rspec/gems/capybara-3.0.2/lib/capybara/session.rb:126:in `reset!'
     # /Users/dunban1/.rvm/gems/ruby-2.3.0@rspec/gems/capybara-3.0.2/lib/capybara.rb:308:in `block in reset_sessions!'
     # /Users/dunban1/.rvm/gems/ruby-2.3.0@rspec/gems/capybara-3.0.2/lib/capybara.rb:308:in `reverse_each'
     # /Users/dunban1/.rvm/gems/ruby-2.3.0@rspec/gems/capybara-3.0.2/lib/capybara.rb:308:in `reset_sessions!'
     # /Users/dunban1/.rvm/gems/ruby-2.3.0@rspec/gems/capybara-3.0.2/lib/capybara/rspec.rb:18:in `block (2 levels) in <top (required)>'

Finished in 54.79 seconds (files took 0.46071 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./spec/example-rspec-capybara.rb:184 # EXAMPLE TESTS ssl cert
rspec ./spec/example-rspec-capybara.rb:195 # EXAMPLE TESTS close page with alert open
```

**Comment by dunban1** [comment] 2018-05-10 20:33
@twalpole I am trying to see if I use FF Nightly (61.0a1) whether I can reproduce what you are seeing. Is this how you use it? 

```
Capybara.register_driver :selenium do |app|
    options = Selenium::WebDriver::Firefox::Options.new
    options.profile = 'default'
    #https://github.com/SeleniumHQ/selenium/wiki/Ruby-Bindings#ssl-certificates
    desired_caps = Selenium::WebDriver::Remote::Capabilities.firefox(
      {
        marionette: true,
        accept_insecure_certs: true,
      }
    )
    
    Capybara::Selenium::Driver.new(
      app,
      browser: :firefox,
      options: options,
      desired_capabilities: desired_caps,
      driver_path: '/Applications/Firefox Nightly.app/Contents/MacOS/firefox'
    )
  end
  Capybara.current_driver = :selenium
```

It opens the browser up for me but the tests don't run. Am I initializing it correctly?

**Comment by twalpole** [comment] 2018-05-10 20:41
@dunban1 Don't know, as I said I'm on FF 61.0b3 ( the beta channel not 62.0a1 which would be the current nightly) and it produces

```
Config: .env
WebDriver: FIREFOX-SAVED-PROFILE
FireFox Profile: default
..

Finished in 16.99 seconds (files took 0.45285 seconds to load)
2 examples, 0 failures
```

so I'm assuming it's a change around modal handling in FF 61 - I know FF has been making a number of changes recently around modal handling in marionette so it's definitely possible some are in 61.

**Comment by twalpole** [comment] 2018-05-10 20:46
To use the alpha you probably want to set 

    Selenium::WebDriver::Firefox.path = <path to Firefox executable>

but I have no clue whether the alpha is compatible with the current geckodriver

**Comment by dunban1** [comment] 2018-05-10 21:11
@twalpole Thanks. The following works for running the tests but the timeout is still happening:
`Selenium::WebDriver::Firefox.path = '/Applications/Firefox Nightly.app/Contents/MacOS/firefox'`
If I remove the profile from the initialization then it runs fine.  

I downloaded the beta channel 61.0b3 (64-bit) and ran it as well. Again with the profile I get the timeout without the profile, it runs just fine.

**Comment by twalpole** [comment] 2018-05-10 21:13
@dunban1 Then it sounds like you have made changes in the default profile that have changed Firefoxes default behavior in a negative way.

**Comment by dunban1** [comment] 2018-05-11 22:03
@twalpole Thanks for looking into this. I verified that it was indeed a corrupted profile. I deleted the profile and it worked.
