### ISSUE TITLE
StaleElementReferenceError for Chrome

### ISSUE THREAD

**Issue by piotrzk** [jnicklas/capybara#1563] opened 2015-08-17 14:59 UTC
Hi,

I have tests that quite smoothly works with Firefox but after changing browser to Chrome I've started getting:
```
Selenium::WebDriver::Error::StaleElementReferenceError: stale element reference: element is not attached to the page document
  (Session info: chrome=44.0.2403.155)
  (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.10.5 x86_64)
```

Any ideas or hints how to cope with it?

**Comment by twalpole** [comment] 2015-08-17 17:38
This is a duplicate of #1553

**Closed by twalpole** 2015-08-17 17:38 UTC
