### ISSUE TITLE
Make elements returned by `all` and `first` reloadable

### ISSUE THREAD

**Issue by abotalov** [jnicklas/capybara#1410] opened 2014-09-28 17:59 UTC
I think it would be a good idea to make elements returned by `Finders#all` reloadable, i.e.:
* set `Element#allow_reload` to true for every element from returned result. It may be done inside `Finders#all` or `Query#resolve_for`
* Pass `index` as the last argument inside `Query#resolve_for` (It will be not required argument that defaults to `0` just to not break backwards compatibility as `@api private` isn't added for `Element#initialize`)
* Inside `Element#reload` use `all(...)[index]` instead of `first(...)`

Do you like that idea?

**Comment by twalpole** [comment] 2015-01-14 18:55
Closing this due to jnicklas huge :-1: and potential unexpected behavior it introduces

**Closed by twalpole** 2015-01-14 18:55 UTC
