### ISSUE TITLE
within conflicts with RSpec 3

### ISSUE THREAD

**Issue by bilus** [jnicklas/capybara#1526] opened 2015-06-03 12:56 UTC
Use this self-contained gist to recreate the issue:
https://gist.github.com/bilus/7213a2914a8bb33cefb7

Dependencies:
ruby 2.1.2
capybara 2.4.4
rspec 3.2.0
sinatra 1.4.6

Problem: It doesn't fill in email and name, `find` doesn't work as well. 

To make it pass, comment out `include RSpec::Matchers` in line 38.

**Comment by abotalov** [comment] 2015-06-03 13:23
Duplicate of https://github.com/jnicklas/capybara/issues/1361

**Comment by bilus** [comment] 2015-06-03 13:31
#1361 has been closed and the problem is a real one (as is the `all` issue). It cost me several hours to narrow down the issue and figure out what is wrong after upgrading gems in a large project.

As far as I can tell, the docs don't reflect it while declaring compatibility with RSpec. I think adding at least a note to Readme would be in order, perhaps a warning. If there's support for that, I'd be more than happy to submit a PR with a Readme update.

**Comment by twalpole** [comment] 2015-06-03 17:20
Happy to review a PR for the Readme, but theres really not much we can do about this -- we can't stop other includes from overriding methods.

**Comment by twalpole** [comment] 2015-06-03 18:05
I guess we could override include on the class Capybara::DSL is included to and then check if RSpec::Matchers is included after and issue a warning.   Something like 

    def self.included(base)
      base.instance_eval do
        def include(*modules)
          orig_modules = included_modules
          super
          new_modules = included_modules - orig_modules
          if new_modules.any? { |mod| mod.to_s == 'RSpec::Matchers' }
            warn "RSpec::Matchers included after Capybara::DSL will shadow #within and #all - Use page.within and page.all instead to access Capybara functionality"
          end
        end
      end

      warn "including Capybara::DSL in the global scope is not recommended!" if base == Object
      super
    end

Not sure if thats a good idea or not

**Comment by cris** [comment] 2015-06-03 22:23
@bilus looks like `RSpec::Matchers` works differently when using in `minitest` and `rspec`. There is no issue with RSpec+Capybara and `within` matcher. In RSpec it's `be_within` and it works fine without affecting Capybara `within`.

You can switch to `RSpec` instead of `minitest`. Here is your example pass without collision:

    require 'sinatra'

    get '/' do
      <<HTML
    <!DOCTYPE html>
    <html>
    <head lang="en">
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
    <h1>Title</h1>
    <form id="main-form" action="/" method="post">
        <input type="text" name="email">
        <br>
        <input type="text" name="name">
        <br>
        <input type="submit" value="submit">
    </form>
    </body>
    </html>
    HTML
    end

    post '/' do
      'Congratulations'
    end

    require 'capybara'
    require 'rspec'
    require 'capybara/rspec'

    Capybara.app = Sinatra::Application

    feature 'cool test' do
      scenario 'title exists' do
        visit '/'
        within('#main-form') do
          fill_in 'email', with: 'user@example.com'
          fill_in 'name', with: 'Joe Public'
          click_button 'submit'
        end
        expect(page).to have_content('Congratulations')
      end
    end

**Comment by bilus** [comment] 2015-06-03 22:55
In production I'm using Cucumber not minitest. I've used minitest to
recreate this issue only.

**Comment by cris** [comment] 2015-06-04 17:57
@bilus 

For this simple app, to make test pass, you need only to swap `include`s:

    class TestApp < MiniTest::Unit::TestCase
      include RSpec::Matchers
      include Capybara::DSL

      def test_title_exists
        visit '/'
        within('#main-form') do
          fill_in 'email', with: 'user@example.com'
          fill_in 'name', with: 'Joe Public'
          click_button 'submit'
        end
        assert has_content?('Congratulations')
      end
    end

In this way `Capybara::DSL` overwrites `within` from `RSpec::Matchers` and test pass. I don't know, how you setup your Cucumber configuration. But try to change the way you `include` module or `require` library. So RSpec should go before Capybara.

**Comment by cris** [comment] 2015-06-04 18:03
@bilus 
Also, as an option, you can remove `within` method: `RSpec::Matchers.send :remove_method, :within` before including `RSpec::Matchers`:

    Capybara.app = Sinatra::Application
    RSpec::Matchers.send :remove_method, :within

    class TestApp < MiniTest::Unit::TestCase
      include Capybara::DSL
      include RSpec::Matchers

      def test_title_exists
        visit '/'
        within('#main-form') do
          fill_in 'email', with: 'user@example.com'
          fill_in 'name', with: 'Joe Public'
          click_button 'submit'
        end
        assert has_content?('Congratulations')
      end
    end

**Comment by bilus** [comment] 2015-06-05 09:26
Thanks! I think the easiest way might be to just use `page.within`
consistently in all tests. That's what I've actually done in the original
project.

**Closed** 2015-10-29 23:11 UTC

**Comment by bjornlinder** [comment] 2016-02-05 00:14
Good tip on remove_method! I took out the method for Capybara due to name conflict with the geokit-rails gem: `Capybara::DSL.send :remove_method, :within`

**Comment by twalpole** [comment] 2016-02-05 00:32
@bjornlinder RSpec and Capybara make sense to be included into the same scope - but why would geokit-rails include a #within method into test cases ? It would seem it should only be included into the models that are declared acts_as_mappable. (or why are you including Capybara::DSL into models, if thats what you're doing)

**Comment by bjornlinder** [comment] 2016-02-05 18:24
I'm not including Capybara into models - the geokit #within method gets called as part of the integration tests. Capybara is available in the model because the query is running in the test environment.

**Comment by twalpole** [comment] 2016-02-05 18:58
@bjornlinder The geokit-rails gem only includes the #within method into ActiveRecord::Base derived classes correct? And Capybaras DSL methods should only be included into whatever feature/integration test class is being used (definitely not into ActiveRecord::Base derived classes - so it shouldn't be available in any models) - so I'm not fully understanding how there would ever be a conflict.

**Comment by bjornlinder** [comment] 2016-02-05 21:23
Why Capybara is available from models when running tests, I don't know either. Not getting any errors about Capybara being in the global scope.

**Comment by twalpole** [comment] 2016-02-05 22:00
search for "include Capybara::DSL"  in your code and see if maybe you're including it somewhere it shouldn't be -  including it into models could cause all sorts of weird issues during testing - and none of Capybaras files do that - you can also check Object.included_modules and Object.ancestors to see what has been included into the global object, and the same on things like ActiveRecord::Base to see there too
