### ISSUE TITLE
selenium webdriver :  problem with javascript menu 

### ISSUE THREAD

**Issue by rwobben** [jnicklas/capybara#1706] opened 2016-06-06 13:56 UTC
Hello, 

I have this menu in rails : 

    
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
          <div class="menu_section">
            <h3>General</h3>
            <ul class="nav side-menu">
              <li>
                <%= link_to root_path do  %>
                    <i class="fa fa-home"></i> Home</a>
                 <% end %>
              </li>
              <li><a><i class="fa fa-money"></i>  Boekhouding <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li>
                    <%= link_to "Rekening schema", accounts_path %>
                   </li>
                </ul>
              </li>
             </ul>
          </div>
        </div>

where he boekhouding choice needs to be clicked so the rekening schema choice is visible.

Now I test the menu like this : 

    require 'rails_helper'

    RSpec.feature 'Users can enter accounts' do

      scenario 'a valid data', js:true do
         visit '/'
        find('a', :text => 'Boekhouding').click
        find('a', :text => 'Rekening schema').click
        expect(page).to have_current_path(accounts_path)
        find('a', :text => 'Nieuwe rekening').click
        fill_in 'Name' 'test_account'
        select 'bezitting langer dan 1 jaar', :from => 'CategorySelect'
        click_button 'Create Account'
        expect(page).to have_content 'Account has been created.'
       end

    end

this one fails with this message : 

       expected "/" to equal "/accounts" 
    ./spec/features/test_menu_spec.rb:9:in `block (2 levels) in <top (required)>'

when I change the webdriver to webkit everythings works fine

**Comment by twalpole** [comment] 2016-06-07 09:02
Please ask howto questions on the mailing list as requested in the README.  If you think you've found an actual issue with Capybara then please provide a reproducible example that we can test with.

**Comment by rwobben** [comment] 2016-06-07 10:43
I think I have found a actual issue. 
I have given the rails and test data which you can test on in my first respons. 

if you need more , im willing to give you more info.
You can also use alll the code of the site, Im making now.
The url is :  https://github.com/rwobben/paytime

so to reproduce this : 

1) clone my repo : git clone https://github.com/rwobben/paytime.git
2)  bundle install
3) rspec

**Comment by twalpole** [comment] 2016-06-07 18:29
This is intermittent because you have an issue with animation -- while the link is moving its possible for a click to occur in the wrong place and therefore be ignored (or be clicked in the right place but swallowed by one of the JS libraries while its sliding down) - You can either put a slight delay between the two clicks to make sure the animation has finished, or a better solution (which will also make your tests faster) is to disable animations during testing.  Since you're using jquery and bootstrap you can disable the animations by adding the following in your layout after the include for application.js

    <%= javascript_tag do %>
      $.support.transition = false; // disable Bootstrap animations
     $.fx.off = true; // disable jQuery animations
    <% end if Rails.env.test? %>

**Closed by twalpole** 2016-06-07 18:29 UTC
